- name: Install APT packages
  hosts: localhost
  gather_facts: true
  become: true
  tasks:
    - name: Install system dependencies
      ansible.builtin.apt:
        state: present
        update_cache: true
        install_recommends: true
        name:
          # system
          - ubuntu-minimal
          - ubuntu-server
          - ubuntu-standard
          # utilities
          - locales-all
          - lsb
          - ifupdown-extra
          - grepcidr
          - errno
          - parallel
          - expect
          - mle
          - p7zip-full
          - neofetch
          - httpie
          - aria2
          - bat
          - tree
          - zsh
          - acl
          - net-tools
          - docker-ce
          - docker-compose
          - podman-toolbox
          - enca
          - gh
          - kubectl
          - helm
          - terraform
          - ansible-lint
          # development
          - build-essential
          - g++-multilib
          - gcc-opt
          - mold
          - cmake-extras
          - meson
          - gdb
          - uuid-dev
          - gdc
          - gcovr
          - lcov
          - flex
          - bison
          - git-all
          - git-ftp
          - git-lfs
          - git-review
          - grip
          - subversion
          - ruby-all-dev
          - ruby-full
          - python3-all-dev
          - gradle
          - maven
          - default-jdk
          - valgrind-mpi
          - cppcheck
          - cpplint
          - iwyu
          - shfmt
          - shellcheck
          - rust-all
          - cargo
          - nodejs
          - patchelf
          - lz4
          - cpuinfo
          - crudini
          # libraries
          - inotify-tools
          - packaging-dev
          - libdpkg-dev
          - librpm-dev
          - libssh-dev
