- name: Install CLI tools
  hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: Install GitLab CLI
      glab_cli:
        version: "1.91.0"
        os: linux
        arch: amd64
    - name: Install Rancher CLI
      rancher_cli:
        version: "2.14.0"
        os: linux
        arch: amd64
    - name: Install Claude CLI
      claude_cli:
        version: "2.1.92"
        os: linux
        arch: x64
    - name: Install Cursor CLI
      cursor_cli:
        version: "2026.03.30-a5d3e17"
        os: linux
        arch: x64
    - name: Install uv
      astral_cli:
        tool: uv
        version: "0.11.3"
        arch: x86_64
        platform: unknown
        os: linux
        abi: gnu
    - name: Install ruff
      astral_cli:
        tool: ruff
        version: "0.15.9"
        arch: x86_64
        platform: unknown
        os: linux
        abi: gnu
    - name: Install ty
      astral_cli:
        tool: ty
        version: "0.0.28"
        arch: x86_64
        platform: unknown
        os: linux
        abi: gnu
    - name: Install Helm push plugin
      helm_push_plugin:
        prefix: ~/.local/share/helm/plugins
        version: "0.11.1"
        os: linux
        arch: amd64
      become: false
    - name: Install Helm diff plugin
      helm_diff_plugin:
        prefix: ~/.local/share/helm/plugins
        version: "3.15.4"
        os: linux
        arch: amd64
      become: false
