- name: Add git repositories to home folder
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Clone repositories
      ansible.builtin.git:
        clone: true
        dest: "{{ ansible_user_dir }}/{{ item.path }}"
        force: false
        recursive: true
        repo: "git@github.com:{{ item.repo }}.git"
        update: true
        version: "{{ item.version }}"
      loop:
        - path: .nano
          repo: scopatz/nanorc
          version: master
        - path: .ohmybash
          repo: ohmybash/oh-my-bash
          version: master
        - path: .ohmyzsh
          repo: ohmyzsh/ohmyzsh
          version: master
        - path: .ohmyzsh/custom/plugins/zsh-autosuggestions
          repo: zsh-users/zsh-autosuggestions
          version: master
        - path: .ohmyzsh/custom/plugins/zsh-completions
          repo: zsh-users/zsh-completions
          version: master
        - path: .ohmyzsh/custom/plugins/zsh-syntax-highlighting
          repo: zsh-users/zsh-syntax-highlighting
          version: master
        - path: .ohmyzsh/custom/plugins/conda-zsh-completion
          repo: conda-incubator/conda-zsh-completion
          version: main
        - path: .ohmyzsh/custom/powerlevel10k
          repo: romkatv/powerlevel10k
          version: master
        - path: .vim_runtime
          repo: amix/vimrc
          version: master
    - name: Symlink Powerlevel10k theme
      ansible.builtin.file:
        dest: "{{ ansible_user_dir }}/.ohmyzsh/custom/themes/powerlevel10k.zsh-theme"
        src: "{{ ansible_user_dir }}/.ohmyzsh/custom/powerlevel10k/powerlevel10k.zsh-theme"
        state: link
    - name: Run vimrc installation script
      ansible.builtin.command:
        argv:
          - "{{ ansible_user_dir }}/.vim_runtime/install_awesome_vimrc.sh"
        chdir: "{{ ansible_user_dir }}"
        creates: "{{ ansible_user_dir }}/.vimrc"
    - name: Copy .nanorc
      ansible.builtin.copy:
        dest: "{{ ansible_user_dir }}/.nanorc"
        group: "{{ ansible_user_gid }}"
        mode: "0644"
        owner: "{{ ansible_user_id }}"
        src: "{{ ansible_user_dir }}/.nano/nanorc"
