- name: Configure mounts
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Unmount swap
      ansible.posix.mount:
        path: none
        state: unmounted
    - name: Disable swap
      ansible.posix.mount:
        path: none
        state: absent
    - name: Create primary mount points
      ansible.builtin.file:
        group: root
        mode: "0755"
        owner: root
        path: "{{ item }}"
        state: directory
      loop:
        - /boot/cloudinit
        - /boot/efi
    - name: Mount EFI partition
      ansible.posix.mount:
        dump: 0
        fstype: vfat
        opts: defaults
        passno: 2
        path: /boot/efi
        src: /dev/disk/by-id/nvme-{{ disks[efi.disk] }}-part{{ efi.partition }}
        state: mounted
    - name: Mount cloudinit partition
      ansible.posix.mount:
        dump: 0
        fstype: vfat
        opts: defaults
        passno: 2
        path: /boot/cloudinit
        src: /dev/disk/by-id/nvme-{{ disks[cloudinit.disk] }}-part{{ cloudinit.partition }}
        state: mounted
    - name: Mount disk partitions
      ansible.posix.mount:
        dump: "{{ item.dump | default(0) }}"
        fstype: "{{ item.filesystem | default('ext4') }}"
        opts: "{{ item.options | default('defaults') }}"
        passno: "{{ item.passno | default(2) }}"
        path: "{{ item.mountpoint }}"
        src: /dev/disk/by-id/nvme-{{ disks[item.disk] }}-part{{ item.partition }}
        state: mounted
      loop: "{{ diskmount | default([]) }}"
      loop_control:
        label: "{{ item.mountpoint }}"
    - name: Mount tmpfs
      ansible.posix.mount:
        dump: 0
        fstype: tmpfs
        opts: "{{ item.opts }}"
        passno: 0
        path: "{{ item.path }}"
        src: tmpfs
        state: mounted
      loop: "{{ tmpfs | default([]) }}"
      loop_control:
        label: "{{ item.path }}"
    - name: Mount NFS shares
      ansible.posix.mount:
        dump: 0
        fstype: nfs
        opts: _netdev,nodev,nofail,nosuid,nfsvers=3,proto=tcp,retrans=3,rsize=1048576,soft,timeo=600,wsize=1048576
        passno: 0
        path: "{{ item.path }}"
        src: "{{ item.src }}"
        state: mounted
      loop: "{{ nfs | default([]) }}"
      loop_control:
        label: "{{ item.path }}"
