line-length = 120
indent-width = 4
target-version = "py312"

[lint]
select = ["A", "ANN", "ARG", "C4", "DTZ", "E", "F", "G", "I", "LOG", "N", "PERF", "RUF", "S", "SLOT", "TID", "W"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
