- name: Modify user settings
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Edit /etc/login.defs
      ansible.builtin.lineinfile:
        backrefs: true
        backup: false
        create: false
        group: root
        line: "\\1 {{ item.value }}"
        mode: "0644"
        owner: root
        path: /etc/login.defs
        regexp: "^#?\\s*({{ item.key }})\\s+"
        state: present
      loop:
        - key: HOME_MODE
          value: "0750"
        - key: UMASK
          value: "022"
        - key: USERGROUPS_ENAB
          value: "no"
      loop_control:
        label: "{{ item.key }} => {{ item.value }}"
    - name: Create system groups
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
        system: true
      loop:
        - docker
        - ssl-cert
        - www-data
    - name: Create users
      ansible.builtin.user:
        append: false
        create_home: true
        group: "{{ item.value.group }}"
        groups: "{{ item.value.groups }}"
        home: "{{ item.value.home }}"
        move_home: false
        name: "{{ item.key }}"
        password: "!"
        shell: "{{ item.value.shell | default('/bin/bash') }}"
        system: false
        uid: "{{ item.value.uid | default(omit) }}"
        umask: "027"
        update_password: on_create
      loop: "{{ users | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
    - name: Remove group same as user
      ansible.builtin.group:
        name: "{{ item.key }}"
        state: absent
      loop: "{{ users | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
    - name: Configure SSH keys
      ansible.posix.authorized_key:
        exclusive: true
        follow: false
        key: "{{ item.value.ssh_keys }}"
        manage_dir: true
        state: present
        user: "{{ item.key }}"
      when: item.value.ssh_keys is defined
      loop: "{{ users | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
    - name: Fix .ssh directory permissions
      ansible.builtin.file:
        path: "{{ item.value.home }}/.ssh"
        owner: "{{ item.key }}"
        group: "{{ item.value.group }}"
        mode: "0700"
        state: directory
      when: item.value.ssh_keys is defined
      loop: "{{ users | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
    - name: Fix authorized_keys permissions
      ansible.builtin.file:
        path: "{{ item.value.home }}/.ssh/authorized_keys"
        owner: "{{ item.key }}"
        group: "{{ item.value.group }}"
        mode: "0600"
        state: file
      when: item.value.ssh_keys is defined
      loop: "{{ users | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
    - name: Configure passwordless sudo
      ansible.builtin.copy:
        content: |
          {% for user in users %}
          {{ user }} ALL=(ALL:ALL) NOPASSWD: ALL
          {% endfor %}
        dest: /etc/sudoers.d/00-localusers
        group: root
        mode: "0440"
        owner: root
        validate: 'visudo -cf %s'
    - name: Purge legacy sudoer files
      ansible.builtin.file:
        path: "/etc/sudoers.d/{{ item.key }}"
        state: absent
      loop: "{{ users | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
