version: 2.1
jobs:
  ubuntu:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run: bash ubuntu.sh
workflows:
  version: 2
  ubuntu-tests:
    jobs:
      - ubuntu:
          filters:
            branches:
              only: master
