version: 2.1
commands:
  ubuntu-test:
    parameters:
      config:
        type: string
    steps:
      - checkout
      - run: bash ubuntu/<< parameters.config >>.sh -d bionic -l au
jobs:
  ubuntu-base:
    docker:
      - image: ubuntu:bionic
    steps:
      - ubuntu-test:
          config: base
  ubuntu-desktop:
    docker:
      - image: ubuntu:bionic
    steps:
      - ubuntu-test:
          config: extra
workflows:
  version: 2
  multiple-tests:
    jobs:
      - ubuntu-base:
          filters:
            branches:
              only: master
      - ubuntu-desktop:
          filters:
            branches:
              only: master
