name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - ansible
  - autopep8
  - babel
  - beautifulsoup4
  - cffi
  - conda
  - conda-env
  - conda-verify
  - cython
  - cytoolz
  - docker-compose
  - docker-py
  - flask
  - flask-cors
  - future
  - ipykernel
  - ipyparallel
  - ipython
  - ipywidgets
  - jpeg
  - jupyter
  - jupyterlab
  - jupyter_contrib_nbextensions
  - markdown
  - more-itertools
  - multipledispatch
  - mypy
  - nb_conda
  - notebook
  - openstacksdk
  - pathlib2
  - pcre
  - pefile
  - pep8
  - pep8-naming
  - pillow
  - pip
  - psutil
  - pycodestyle
  - pycurl
  - pylint
  - python
  - requests
  - selenium
  - simplegeneric
  - singledispatch
  - sortedcollections
  - toolz
  - typing
  - widgetsnbextension
  - wxpython
