name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - anaconda
  - anaconda-client
  - anaconda-navigator
  - anaconda-project
  - astroid
  - astropy
  - atomicwrites
  - automat
  - autopep8
  - babel
  - backports
  - beautifulsoup4
  - bitarray
  - blas
  - bleach
  - bokeh
  - bzip2
  - cffi
  - conda
  - conda-build
  - conda-env
  - conda-verify
  - cython
  - cytoolz
  - dask
  - dask-core
  - datashape
  - docutils
  - flask
  - flask-cors
  - freetype
  - future
  - gensim
  - hyperlink
  - icu
  - importlib_metadata
  - intel-openmp
  - ipykernel
  - ipyparallel
  - ipython
  - ipython_genutils
  - ipywidgets
  - isort
  - jpeg
  - jupyter
  - jupyterlab
  - jupyter_contrib_nbextensions
  - libarchive
  - libcurl
  - libiconv
  - libpng
  - libssh2
  - libtiff
  - libxml2
  - libxslt
  - llvmlite
  - lzo
  - markdown
  - markupsafe
  - matplotlib
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - more-itertools
  - mpmath
  - msgpack-python
  - multipledispatch
  - mypy
  - mypy_extensions
  - navigator-updater
  - nb_anacondacloud
  - nb_conda
  - nb_conda_kernels
  - nbbrowserpdf
  - nbconvert
  - nbformat
  - nbpresent
  - networkx
  - nltk
  - nose
  - notebook
  - numba
  - numexpr
  - numpy
  - numpy-base
  - numpydoc
  - openssl
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - pathlib2
  - pefile
  - pep8
  - pep8-naming
  - pexpect
  - pillow
  - pip
  - psutil
  - pycodestyle
  - pycrypto
  - pycurl
  - pylint
  - pyodbc
  - pyopenssl
  - pyparsing
  - pyside
  - pysocks
  - pytables
  - pytest
  - pytest-arraydiff
  - pytest-astropy
  - pytest-doctestplus
  - pytest-openfiles
  - pytest-remotedata
  - python
  - python-dateutil
  - python-libarchive-c
  - pyyaml
  - pyzmq
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - scrapy
  - seaborn
  - setuptools
  - simplegeneric
  - singledispatch
  - sip
  - six
  - snappy
  - sortedcollections
  - sortedcontainers
  - spacy
  - sphinx
  - sphinxcontrib
  - sphinxcontrib-websupport
  - spyder
  - spyder-kernels
  - statsmodels
  - sympy
  - theano
  - tk
  - tqdm
  - typed-ast
  - typing
  - unicodecsv
  - urllib3
  - webencodings
  - werkzeug
  - wheel
  - whoosh
  - widgetsnbextension
  - wxpython
  - xlrd
  - xlsxwriter
  - xz
  - yaml
  - zeromq
  - zlib
