- name: "Add {{ name }} APT Key"
  apt_key:
    state: present
    file: "{{ key.file | default(omit) }}"
    url: "{{ key.url | default(omit) }}"
    keyring: "/etc/apt/trusted.gpg.d/{{ name }}.gpg"
  when: "key.replace | default(True)"
- name: "Add {{ name }} APT repositories"
  apt_repository:
    state: present
    repo: "deb {{ item[0] }} {{ item[1] }} {{ components_string }}"
    filename: "{{ name }}"
    update_cache: no
  with_nested:
    - "{{ repo.urls | select }}"
    - "{{ repo.distributions | select }}"
  vars:
    components_string: "{{ repo.components | default([]) | select | join(' ') }}"
